[mypy]
warn_return_any        = 1
warn_unused_configs    = 1
warn_unreachable       = 1
strict_optional        = 1
ignore_missing_imports = 1
disallow_any_generics  = 1
disallow_untyped_defs  = 1
check_untyped_defs     = 1
show_none_errors       = 1

