[mypy]
warn_return_any        = True
warn_unused_configs    = True
warn_unreachable       = True
strict_optional        = True
ignore_missing_imports = True
disallow_any_generics  = True
disallow_untyped_defs  = True
check_untyped_defs     = True
show_none_errors       = True

