name: 🤛 Compare

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths: ['documents/**']

jobs:
  build-review:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ykyki/docker-tex-image:1.0
      options: --user root
      credentials:
        username: ykyki
        password: ${{ secrets.DOCKER_LOGIN_PASS }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: '0'
    - run: git branch
    - name: check current status
      run: |
        whoami
        pwd
        ls -l
        git status
    - name: build updated files
      run: git diff --name-only origin/develop ./documents/catalog | xargs -P0 -L1 -I {} sh ./tools/build.sh {} review
    - name: Set vars
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - uses: actions/upload-artifact@v3
      with:
        name: extop-tex-${{ steps.vars.outputs.sha_short }}
        path: ./temp/*.pdf
