name: 🤛 Compare

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths: ['documents/**']

jobs:
  build-review:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ykyki/docker-texlive-2020:1.1
      options: --user root
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: '0'
    - run: git branch
    - name: check current status
      run: |
        whoami
        pwd
        ls -l
        git status
    - name: build updated files
      run: |
        git diff --name-only --diff-filter=AM origin/develop \
        ./documents/catalog/root.tex \
        ./documents/catalog/theories \
        ./documents/catalog/examples \
        | grep ".tex" \
        | xargs -P4 -L1 -I {} sh ./tools/build.sh {} review
    - name: Set vars
      id: vars
      run: |
        echo "::set-output name=branch_name::$(echo $GITHUB_HEAD_REF | sed 's|/|_|g')"
    - uses: actions/upload-artifact@v3
      with:
        name: extop-tex-compare-${{ github.run_number }}-${{ steps.vars.outputs.branch_name }}
        path: ./outputs/
